export default function TermsOfService() {
  return (
    <main className="min-h-screen bg-gray-950 text-gray-100 px-4 py-12">
      <div className="max-w-2xl mx-auto">

        {/* Header */}
        <div className="mb-10">
          <a href="/" className="text-sm text-gray-500 hover:text-gray-300 transition-colors mb-6 inline-block">
            ← Back to IsItAScam
          </a>
          <h1 className="text-3xl font-bold text-white mb-2">Terms of Service</h1>
          <p className="text-gray-400 text-sm">
            IsItAScam — operated by JAGA Technologies<br />
            Last updated: April 2026
          </p>
        </div>

        <div className="space-y-8 text-gray-300 leading-relaxed text-sm">

          <section>
            <h2 className="text-white font-semibold text-base mb-3">1. Acceptance of Terms</h2>
            <p>
              By using IsItAScam, you agree to these Terms of Service. If you do not agree, do not use the app.
            </p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-3">2. Description of Service</h2>
            <p>
              IsItAScam provides AI-powered analysis of text, images, and QR codes to help users identify
              potential scams. Results are generated by artificial intelligence and are provided for
              informational purposes only.
            </p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-3">3. No Guarantee of Accuracy</h2>
            <p>
              IsItAScam does not guarantee that any analysis result is accurate, complete, or reliable.
              AI-generated verdicts may contain errors. Users must exercise their own judgment and must not
              rely solely on any result provided by this app for financial, legal, or personal decisions.
            </p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-3">4. Limitation of Liability</h2>
            <p className="mb-3">
              To the fullest extent permitted by Malaysian law, JAGA Technologies shall not be liable
              for any loss, damage, or harm arising from:
            </p>
            <ul className="space-y-2 pl-4">
              <li className="flex gap-2"><span className="text-gray-500 mt-0.5">•</span><span>Reliance on any verdict or result generated by the app</span></li>
              <li className="flex gap-2"><span className="text-gray-500 mt-0.5">•</span><span>Financial losses resulting from scam incidents</span></li>
              <li className="flex gap-2"><span className="text-gray-500 mt-0.5">•</span><span>Inaccurate or incomplete analysis results</span></li>
              <li className="flex gap-2"><span className="text-gray-500 mt-0.5">•</span><span>Service interruptions or downtime</span></li>
            </ul>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-3">5. User Responsibilities</h2>
            <p className="mb-3">You agree not to use IsItAScam to:</p>
            <ul className="space-y-2 pl-4">
              <li className="flex gap-2"><span className="text-gray-500 mt-0.5">•</span><span>Submit content that is illegal under Malaysian law</span></li>
              <li className="flex gap-2"><span className="text-gray-500 mt-0.5">•</span><span>Attempt to reverse-engineer or exploit the service</span></li>
              <li className="flex gap-2"><span className="text-gray-500 mt-0.5">•</span><span>Submit false or misleading information</span></li>
              <li className="flex gap-2"><span className="text-gray-500 mt-0.5">•</span><span>Use the service in any way that could harm other users</span></li>
            </ul>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-3">6. Intellectual Property</h2>
            <p>
              All content, design, and technology within IsItAScam is owned by JAGA Technologies.
              You may not reproduce or distribute any part of the service without written permission.
            </p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-3">7. Feedback</h2>
            <p>
              By submitting feedback on scan results, you grant JAGA Technologies a non-exclusive,
              royalty-free licence to use that feedback to improve the service. Feedback is used solely
              to improve scam detection accuracy for all users.
            </p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-3">8. Changes to Terms</h2>
            <p>
              We may update these Terms at any time. Continued use of the app after changes constitutes
              acceptance of the new Terms.
            </p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-3">9. Governing Law</h2>
            <p>
              These Terms are governed by the laws of Malaysia. Any disputes shall be subject to the
              exclusive jurisdiction of Malaysian courts.
            </p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-3">10. Contact</h2>
            <p>For questions about these Terms, contact us at:</p>
            <div className="mt-2 text-gray-400">
              <p>JAGA Technologies</p>
              <p><span className="text-blue-400">[your email]</span></p>
            </div>
          </section>

        </div>

        <div className="mt-12 pt-8 border-t border-gray-800 text-center text-xs text-gray-600">
          © 2026 JAGA Technologies. All rights reserved.
        </div>

      </div>
    </main>
  );
}